Added refusing start as root
git-svn-id: http://hopmod.googlecode.com/svn/trunk@1914 d7818858-e1b4-11dd-a738-5fe2e3cfbcc5

diff --git a/bin/authserver b/bin/authserver
--- a/bin/authserver
+++ b/bin/authserver
@@ -5,6 +5,15 @@
 
 ################################################################################
 
+# refuse root
+if [ "x${UID}" = "x0" ]
+then
+    echo "You cannot start the server as root!"
+    exit 1
+fi
+
+################################################################################
+
 v_system=$(uname)
 
 f_starter=$(basename $0)
