Check that the server executable file exists before startup in the control script
git-svn-id: http://hopmod.googlecode.com/svn/trunk@2057 d7818858-e1b4-11dd-a738-5fe2e3cfbcc5

diff --git a/bin/server b/bin/server
--- a/bin/server
+++ b/bin/server
@@ -251,7 +251,13 @@ case "$1" in
                 then
                     v_remove_status_log=y
                 fi
-                
+        
+        if [ ! -x bin/sauer_server ]
+        then
+            echo "Cannot find or execute bin/sauer_server"
+            exit 1
+        fi
+        
 		if ! p_start_server
 		then
 		    echo "It appears the game server is already running."
